[package]
name = "day11"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day11-part1"
path = "src/part1.rs"

[[bin]]
name = "day11-part2"
path = "src/part2.rs"

[dependencies]
utils = { path = "../../utils" }
